Repository tfettig22/whats-cookin-group-project, pull requests merged in 2022-08, with the labels that each got.

#69 Refactor getMissingIngredients and display to DOM
  dist/index.html
  src/classes/Pantry.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
Labels: iteration4

#68 Add styling to add ingredient form
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#70 Feature/pantry display and post
  dist/index.html
  src/apiCalls.js
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
Labels: enhancement, iteration4

#71 Docs: add gifs to readme
  README.md
  dist/cook-me.svg
  dist/index.html
  src/styles.css
Labels: documentation
