Repository tfettig22/whats-cookin-group-project, pull requests merged in 2022-07, with the labels that each got.

#3 Feat: Add test file and implementation code for recipe repository class
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/data/recipes.js
  test/RecipeRepository-test.js
Labels: good first issue

#6 Feature/recipe class
  src/classes/Ingredient.js
  src/classes/Recipe.js
  test/Ingredient-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
Labels: iteration1

#10 Finish recipe class testing
  src/classes/Recipe.js
  src/data/ingredients.js
  test/Recipe-test.js
Labels: iteration1

#11 Feature/html build
  dist/index.html
  src/styles.css
Labels: iteration1

#12 Feature/user class
  src/classes/User.js
  src/data/users.js
  test/User-test.js
Labels: iteration2

#13 Refactor: Add quotations around keys in user data file to match original format
  src/data/users.js
Labels: refactor

#15 Feature/header format
  dist/anyonecancook-logo.svg
  dist/favorite 2-100.jpg
  dist/favorite-svg.svg
  dist/favorite.png
  dist/home 2-100.jpg
  dist/home-icon-svg.svg
  dist/home.png
  dist/index.html
  src/images/anyonecancook-logo.svg
  src/images/favorite-svg.svg
  src/images/home-icon-svg.svg
  src/scripts.js
  src/styles.css
Labels: iteration1

#16 Refactor: Fix some html indentation and also rearrange recipe view page
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: iteration1

#17 Feature/radio buttons
  dist/index.html
  src/classes/RecipeRepository.js
  src/scripts.js
Labels: iteration1

#18 Feature/user story recipe selected
  dist/index.html
  src/styles.css
Labels: iteration1

#20 Feature/image styling
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: iteration1

#19 Feature/recipe instructions ingredients
  dist/index.html
  src/classes/Recipe.js
  src/scripts.js
  src/styles.css
  test/Recipe-test.js
Labels: iteration1

#22 Add functions and methods to display all recipe details on recipe page and refactor viewRecipe function to use several helper functions
  src/classes/Recipe.js
  src/scripts.js
  src/styles.css
  test/Recipe-test.js
Labels: iteration1

#23 Feat: Add functions for adding and filtering user favorite recipes array
  dist/index.html
  src/classes/User.js
  src/scripts.js
Labels: iteration2

#24 Feature/favorite page
  dist/index.html
  src/styles.css
Labels: iteration2

#25 Feature/favorite recipes display
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: iteration2

#27 Add saved and delete favorite recipe functionality
  src/scripts.js
  src/styles.css
Labels: iteration2

#34 Feature/fav recipe icon nav
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: iteration2

#31 Feat: add home recipe icon nav to recipe page
  dist/index.html
  src/scripts.js
Labels: iteration2

#35 Feat: add scroll to favorite page and format icons
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: style

#37 Feature/api fetch
  src/apiCalls.js
  src/scripts.js
Labels: iteration3

#40 Feat: format favorites page
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: style

#43 Add final changes to style and fix minor bug in recipes sidebar
  src/scripts.js
  src/styles.css
Labels: bug, style

#44 Docs: add readme
  README.md
Labels: documentation

#45 Refactor/accessibility and tabbing
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: accessibility

#46 Add sad paths and refactor user and recipeRepo tests
  test/RecipeRepository-test.js
  test/User-test.js
Labels: refactor

#47 Add function to hide addToFavorites button when recipe is currently in favorites list
  src/scripts.js
  src/styles.css
Labels: enhancement

#48 Refactor fetch and filter functions
  src/apiCalls.js
  src/scripts.js
Labels: refactor

#50 Feat: add sidebar tags to sidebar
  src/scripts.js
  src/styles.css
Labels: iteration1, refactor, style

#51 Add logic to updateMainPageRecipeIcons function so that it does not repeat icons
  src/scripts.js
Labels: enhancement, refactor

#49 Add tab index to favorite icons and add semi colons and remove extra spaces in html file
  dist/index.html
  src/apiCalls.js
  src/scripts.js
Labels: refactor

#52 Fix minor bug with displaying recipe sidebar title
  src/scripts.js
Labels: bug

#53 Feat: add formatting to side bar by tag
  src/styles.css
Labels: enhancement, refactor, style

#57 Feat: add getMissingIngredients function
  src/classes/Pantry.js
  src/scripts.js
  test/Pantry-test.js
Labels: enhancement, iteration4

#59 Style/style changes home page
  dist/index.html
  src/styles.css
Labels: style

#61 Add get ingredient amounts needed function and test
  src/classes/Pantry.js
  src/data/recipes.js
  src/data/users.js
  test/Pantry-test.js
Labels: iteration4

#62 Feat: add svg files and create grid
  dist/checkmark.svg
  dist/index.html
  dist/spatula.svg
  src/scripts.js
  src/styles.css
Labels: style, iteration4

#64 Feature/add ingredient form
  dist/index.html
  src/apiCalls.js
  src/scripts.js
  src/styles.css
Labels: help wanted, high-priority, iteration4

#63 Add Pantry methods cookRecipe and addIngredient, and add functions to convert ing name to ing id
  dist/index.html
  src/classes/Pantry.js
  src/scripts.js
  test/Pantry-test.js
Labels: enhancement

#65 Display user pantry to DOM
  dist/index.html
  src/classes/Pantry.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
  test/User-test.js
Labels: iteration4
